### ISSUE TITLE
find and confirm the parameterization of OB that Cardano is using in Shelley

### ISSUE THREAD

**Issue by scasplte2** [Topl/Crypto#46]

**Comment by aaronschutza** [comment]
Shelly genesis parameters:
https://github.com/input-output-hk/cardano-node/blob/master/cardano-config/src/Cardano/Config/Shelley/Genesis.hs

**Comment by aaronschutza** [comment]
They have a goal of matching block time with bitcoin.  They very clearly compare themselves and the their own performance criteria with that of bitcoin in the academic papers, the first few pages of OB genesis saying as such.  Additionally, if I'm not mistaken Shelley is using some form of Praos, which has different parameter settings and stake distribution sampling.  Any protocol that relies on the key evolution will require some sort of key rotation since signatures grow in time, but it looks like they cap theirs out.  Key rotation is maybe more of a wallet functionality, at least it could be viewed that way.  There are effectively two wallets, one for the consensus layer that tracks staking tokens and key rotations, and one for the ledger alone.  There is no specification in the design of either Praos or Genesis that limits the age of keys, only that they are securely erased.  The max age is a performance constraint since we don't want ever growing signatures that force the block body size to decrease as time goes on.

They are taking the strategy of setting long epochs and slot times, then constraining them down with each revision of the protocol and testnet to approach more ideal values relative to the performance of the client and the real world network execution, two very big unknowns until the protocol is implemented and tested.

We went straight for Genesis and implemented it in a JVM so we are in a very different position as far as client performance.  I may be wrong but the JVM landscape seems much more developed and robust than the languages they've chosen.  On top of this, purely functional languages are much more difficult to optimize from a developers standpoint.  The abstractions set in place can lead to implementations of algorithms that perform poorly relative to its imperative counterpart.  In my opinion, many constraints set by functional programming are there for the sake of code re-usability, modularity, and brevity, but it is never the case that one chooses a functional language for the sake of performance.

**Comment by aaronschutza** [comment]
There are going to be many changes to the genesis parameters with each revision of the Cardano testnets, we will have to keep up to date with all the developments.  There is a virtual summit that I will be attending: https://cardanosummit.iohk.io/
